#
# packageing_and_upload.yml
#
# These codes are licensed under CC0.
# http://creativecommons.org/publicdomain/zero/1.0/deed.ja
#

name: packaging and upload
on:
  pull_request:
    types: [opened, synchronize]
  release:
    types: [published]

jobs:
  create_package:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: zip
        run: zip -r blender2pmxem.zip . -x  '/*.git/*' '/*.github/*' '/*__pycache_/*' '/*.gitignore' '/*.pep8' '/*tests/*'
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: package
          path: blender2pmxem.zip
      - name: upload to release
        if: github.event_name == 'release'
        uses: JasonEtco/upload-to-release@master
        with:
          args: blender2pmxem.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
