name: pull request check
on: [pull_request]

jobs:
  create_package:
    name: Create Package
    runs-on: unbuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: ls
        run: ls
